package isel.ps.ps_userclient.utils.constants

class ServiceResponses() {
    companion object {
        val SUBSCRIPTIONS_REQUEST_SUCCESS = "SUBSCRIPTIONS_REQUEST_SUCCESS"
        val SUBSCRIPTIONS_REQUEST_FAILURE = "SUBSCRIPTIONS_REQUEST_FAILURE"
        val SEARCH_REQUEST_SUCCESS  = "SEARCH_REQUEST_SUCCESS"
        val SEARCH_REQUEST_FAILURE = "SEARCH_REQUEST_FAILURE"
        val REGISTRATION_SUCCESS = "REGISTRATION_SUCESS"
        val REGISTRATION_FAILURE = "REGISTRATION_FAILURE"
        val LOGIN_SUCCESS = "LOGIN_SUCCESS"
        val LOGIN_FAILURE = "LOGIN_FAILURE"
        val RANKING_POST_SUCESS = "RANKING_POST_SUCESS"
        val RANKING_POST_FAILURE = "RANKING_POST_FAILURE"
        val SUBSCRIPTION_ACTION_SUCCESS = "SUBSCRIPTION_ACTION_SUCCESS"
        val SUBSCRIPTION_ACTION_FAILURE = "SUBSCRIPTION_ACTION_FAILURE"
    }
}
