package isel.ps.ps_userclient.utils.constants

class ServiceResponses {
    companion object {
        val SUBSCRIPTIONS_REQUEST_SUCCESS = "SUBSCRIPTIONS_REQUEST_SUCCESS"
        val SUBSCRIPTIONS_REQUEST_FAILURE = "SUBSCRIPTIONS_REQUEST_FAILURE"
        val SEARCH_REQUEST_SUCCESS  = "SEARCH_REQUEST_SUCCESS"
        val SEARCH_REQUEST_FAILURE = "SEARCH_REQUEST_FAILURE"
        val REGISTRATION_SUCCESS = "REGISTRATION_SUCESS"
        val REGISTRATION_FAILURE = "REGISTRATION_FAILURE"
        val LOGIN_SUCCESS = "LOGIN_SUCCESS"
        val LOGIN_FAILURE = "LOGIN_FAILURE"
        val RANKING_POST_SUCESS = "RANKING_POST_SUCESS"
        val RANKING_POST_FAILURE = "RANKING_POST_FAILURE"
        val SUBSCRIPTION_ACTION_SUCCESS = "SUBSCRIPTION_ACTION_SUCCESS"
        val SUBSCRIPTION_ACTION_FAILURE = "SUBSCRIPTION_ACTION_FAILURE"
        val SERVICE_REQUEST_SUCCESS = "SERVICE_REQUEST_SUCCESS"
        val SERVICE_REQUEST_FAILURE = "SERVICE_REQUEST_FAILURE"
        val USER_EVENTS_REQUEST_SUCCESS = "USER_EVENTS_REQUEST_SUCCESS"
        val USER_EVENTS_REQUEST_FAILURE = "USER_EVENTS_REQUEST_FAILURE"
        val CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
        val CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE"
        val EDIT_USERNAME_SUCCESS = "EDIT_USERNAME_SUCCESS"
        val EDIT_USERNAME_FAILURE = "EDIT_USERNAME_FAILURE"
        val NO_CONNECTION = "NO_CONNECTION"
        val NOTIFICATION_RECEIVED = "NOTIFICATION_RECEIVED"
    }
}
